DISCORD_COMPONENT_TYPE_ACTION_ROW = 1
DISCORD_COMPONENT_TYPE_BUTTON = 2
DISCORD_COMPONENT_TYPE_STRING_SELECT = 3
DISCORD_COMPONENT_TYPE_TEXT_INPUT = 4
DISCORD_COMPONENT_TYPE_USER_SELECT = 5
DISCORD_COMPONENT_TYPE_ROLE_SELECT = 6
DISCORD_COMPONENT_TYPE_MENTIONABLE_SELECT = 7
DISCORD_COMPONENT_TYPE_CHANNEL_SELECT = 8

DISCORD_COMPONENT_TYPES = [
    DISCORD_COMPONENT_TYPE_ACTION_ROW,
    DISCORD_COMPONENT_TYPE_BUTTON,
    DISCORD_COMPONENT_TYPE_STRING_SELECT,
    DISCORD_COMPONENT_TYPE_TEXT_INPUT,
    DISCORD_COMPONENT_TYPE_USER_SELECT,
    DISCORD_COMPONENT_TYPE_ROLE_SELECT,
    DISCORD_COMPONENT_TYPE_MENTIONABLE_SELECT,
    DISCORD_COMPONENT_TYPE_CHANNEL_SELECT,
]

DISCORD_COMPONENT_BUTTON_STYLE_PRIMARY = 1
DISCORD_COMPONENT_BUTTON_STYLE_SECONDARY = 2
DISCORD_COMPONENT_BUTTON_STYLE_SUCCESS = 3
DISCORD_COMPONENT_BUTTON_STYLE_DANGER = 4
DISCORD_COMPONENT_BUTTON_STYLE_LINK = 5

DISCORD_COMPONENT_BUTTON_STYLES = [
    DISCORD_COMPONENT_BUTTON_STYLE_PRIMARY,
    DISCORD_COMPONENT_BUTTON_STYLE_SECONDARY,
    DISCORD_COMPONENT_BUTTON_STYLE_SUCCESS,
    DISCORD_COMPONENT_BUTTON_STYLE_DANGER,
    DISCORD_COMPONENT_BUTTON_STYLE_LINK,
]
